blog/config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/', to: redirect('/articles')

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :articles
  end
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
    validates :content, presence: true, length: { minimum: 10 }
    belongs_to :user
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        if(params[:user_id])
            @user = User.find(params[:user_id])
            @articles = @user.articles.paginate(page: params[:page], per_page: 10).order('created_at DESC')
        else
            @articles = Article.paginate(page: params[:page], per_page: 10).order('created_at DESC')
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)
        print(@article)
        @article.user_id = current_user.id

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    before_action :authenticate_user!, :except => [:index, :show]
    before_action :authenticate_modify_access, :only => [:edit, :destroy]
end

private
    def article_params
        params.require(:article).permit(:title, :content, :post_date)
    end

    def authenticate_modify_access
        @article = Article.find(params[:id])
        if current_user.is_admin or @article.user != current_user
            redirect_to(root_path, :alert => "Permission Denied") and return
        end
    end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        if current_user.is_admin
            @comment = @article.comments.find(params[:id])
            @comment.destroy
        end
        redirect_to article_path(@article)
    end

    before_action :authenticate_user!
    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

blog/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        redirect_to url_for(
            :controller => :articles,
            :action => :index,
            :user_id => params[:id]
        )
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/edit.html.erb
<div class='container'>
    <h3> Edit post </h3>

    <%= form_with(model: @article,  local: true) do |f| %>

        <% if @article.errors.any? %>
            <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this blog from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
        </p>

        <p>
        <%= f.label :content %><br>
        <%= f.text_area :content, cols: "30", rows: "10" %>
        </p>

        <p>
        <%= f.label :post_date %><br>
        <%= f.date_field :post_date %>
        </p>

        <p>
        <%= f.submit %>
        </p>
    <% end %>
</div>

blog/app/views/articles/index.html.erb
<div class='list-container' align='center'>
    <% if @user %>
        <h3>Posts by <%= @user.name %></h3>
    <% end %>

    <table class='list-articles'>
    <% @articles.each do |article| %>
        <tr>
            <td class='td-title'><%= link_to article.title, article_path(article) %></td>
            <td class='td-date'><%= article.post_date %></td>
            <td class='td-edit'><%= link_to 'Edit', edit_article_path(article) %></td>
        </tr>
    <% end %>
    </table>
    <%= will_paginate @articles %>
    <%= link_to 'New Post', new_article_path %>
</div>

blog/app/views/articles/new.html.erb
<div class='container'>
    <h3> Write a new post </h3>

    <%= form_with scope: :article, url: articles_path, local: true do |f| %>
        <% if @article.errors.any? %>
            <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this blog from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <p>
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </p>

        <p>
            <%= f.label :content %><br>
            <%= f.text_area :content, cols: "30", rows: "10" %>
        </p>

        <p>
            <%= f.label :post_date %><br>
            <%= f.date_field :post_date %>
        </p>

        <p>
            <%= f.submit %>
        </p>
    <% end %>
</div>

blog/app/views/articles/show.html.erb
<div class='blog-container'>
    <h3 align='center'>
        <%= @article.title %>
    </h3>

    <p align='right'>
        <% if @article.user %>
            Posted by <%= link_to @article.user.email, user_path(@article.user) %> |
        <% end %>
        <% if current_user and (@article.user == current_user or current_user.is_admin) %>
            <%= link_to 'Edit', edit_article_path %> |
            <%= link_to 'Delete', article_path(@article),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <% end %>
    </p>

    <p align='right'>
        <i><%= @article.post_date %></i>
    </p>

    <p>
    <%= @article.content %>
    </p>
    <% if @article.comments.length > 0 %>
        <h4 class='title'>Comments</h4>
    <% end %>
    <%= render @article.comments %>

    <%= render 'comments/form' %>
</div>

blog/app/views/comments/_comment.html.erb
<p>
    <strong><%= comment.commenter %>:</strong>
    <%= comment.body %>
    <% if current_user and current_user.is_admin %>
        <%= link_to 'Delete', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>

blog/app/views/comments/_form.html.erb
<% if current_user %>
    <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
        <p style="display:none">
            <small><%= form.label :your_name %><br></small>
            <%= form.text_field :commenter, :value => current_user.name %>
        </p>
        <p>
            <small><%= form.label :comment %><br></small>
            <%= form.text_area :body %>
        </p>
        <p>
            <%= form.submit %>
        </p>
    <% end %>
<% else %>
    <div class='alert-success title'> Sign up to comment!</div>
<% end %>

blog/app/views/home/index.html.erb
<h1> Hello, World!</h1>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text">
    <%= link_to 'Home', articles_path, :class => 'navbar-link' %> |
      <%= link_to 'Everyone', users_path %> |
    <% if user_signed_in? %>
      <%= link_to current_user.email, user_path(current_user) %> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= yield %>
  </body>
</html>

blog/app/views/users/index.html.erb
<div class='list-container' align='center'>
    <h3>Everyone...</h3>

    <table class='list-users'>
    <% @users.each_with_index do |user, index| %>
        <tr>
            <td><%= index + 1 %>. <%= link_to user.email, user_path(user) %></td>
        </tr>
    <% end %>
    </table>
</div>